apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jjw09fgd8-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a17f173fce.3bb1.p3.openshiftapps.com/rhtap/rhtap-qe:063cf18722741d50687a5f08819c2feb02a6044a@sha256:6ce67a240dc7747f4ab68c843ba574252b34e07689fb2087c66534aeb21a51f3
          name: container-image
